#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dash-to-dock
Version  : extensions.gnome.org.v64
Release  : 1
URL      : https://github.com/micheleg/dash-to-dock/archive/extensions.gnome.org-v64.tar.gz
Source0  : https://github.com/micheleg/dash-to-dock/archive/extensions.gnome.org-v64.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: dash-to-dock-data = %{version}-%{release}
Requires: dash-to-dock-license = %{version}-%{release}
Requires: dash-to-dock-locales = %{version}-%{release}
BuildRequires : buildreq-gnome

%description
# Dash to Dock
![screenshot](https://github.com/micheleg/dash-to-dock/raw/master/media/screenshot.jpg)

%package data
Summary: data components for the dash-to-dock package.
Group: Data

%description data
data components for the dash-to-dock package.


%package license
Summary: license components for the dash-to-dock package.
Group: Default

%description license
license components for the dash-to-dock package.


%package locales
Summary: locales components for the dash-to-dock package.
Group: Default

%description locales
locales components for the dash-to-dock package.


%prep
%setup -q -n dash-to-dock-extensions.gnome.org-v64

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547130443
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1547130443
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dash-to-dock
cp COPYING %{buildroot}/usr/share/package-licenses/dash-to-dock/COPYING
%make_install
%find_lang dashtodock

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/COPYING
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/README.md
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/convenience.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/intellihide.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/launcherAPI.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/glossy.svg
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/highlight_stacked_bg.svg
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/highlight_stacked_bg_h.svg
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/logo.svg
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js
/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/windowPreview.js

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dash-to-dock/COPYING

%files locales -f dashtodock.lang
%defattr(-,root,root,-)

